# Use an official Python runtime as the base image
FROM python:3.11-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container
COPY requirements.txt /tmp/

# Install the Python dependencies
RUN pip install --no-cache-dir -r /tmp/requirements.txt

# Copy the rest of the application code into the container
COPY . .

# Set the command to run your Python application
CMD ["bash", "-c", "start.sh"]