# Use an official Python runtime as the base image
FROM python:3.11-slim

#Install packages using pkg-config
RUN apt-get update && apt-get install -y pkg-config libmariadb-dev build-essential


# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container
COPY requirements.txt /tmp/

# Install the Python dependencies
RUN pip install --no-cache-dir -r /tmp/requirements.txt

# Delete requirements package in installation
RUN apt-get remove -y build-essential

# Clean apt cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*


# Copy the rest of the application code into the container
COPY . .

# Set the command to run your Python application
CMD ["sh", "/app/start.sh"]