version: '3.8'

services:
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306

    networks:
      - solufit

    env_file:
      - .env

  api:
    build:
      context: .
      dockerfile: ./docker/api/dockerfile
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - db

    networks:
      - solufit

    env_file:
      - .env

volumes:
  db_data:

networks:
  solufit:
    driver: bridge